[package]
name = "noughts-and-crosses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }
# Fixes a bug when compiling
alsa = "=0.6.0"